# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: DISCERN-AIRFLOW-APP CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
  deploy:
   
    needs: build
    runs-on: ubuntu-latest
    name: Deploy to EC2 on master branch push
  
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to AIRFLOW PROD Server 
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DISCERN_STREAM_EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.DISCERN_STREAM_EC2_DNS  }}
          REMOTE_USER: "ubuntu"
          TARGET: "/root/airflow-prod"
    
